### ISSUE TITLE
Command to open new tabs and have hyper-init act on them

### ISSUE THREAD

**Issue by mschmidtkorth** [daltonmenezes/hyper-init#13]
First, thank you for the extension - it is fantastic! I was wondering whether there's a way for hyper-init to basically set all my initial tabs. Right now, all commands are executed in the same pane. Can they be executed in different panes? For example:

- When Hyper is opened
  - cd of the current tab (command 1)
  - Open a new tab (automatically)
  - Execute another command (command 2)
  - …

**Comment by daltonmenezes** [comment]
Hi @mschmidtkorth , thanks.

I believe you can try hyper-init with the [hyperlayout](https://github.com/timolins/hyperlayout) plugin to achieve that.
