### ISSUE TITLE
Can't make this work on Windows 10

### ISSUE THREAD

**Issue by the-glima** [daltonmenezes/hyper-init#2]
Am I doing something wrong?
I've added the configuration, just an example to see working but I only see this:

![terminal](https://user-images.githubusercontent.com/1394578/54695039-8e9e6b80-4b29-11e9-84a1-cc1ce2b7993f.png)

```
plugins: ["hyper-init"],
...
init: [
    {
      rule: 'once',
      commands: ['echo This is only executed on New Windows!']
    }
  ],
...
````

I've removed all others plugins just to make sure but still.

**Comment by daltonmenezes** [comment]
@gabriel-lima-dev , please, see the #1 issue.

**Comment by thesobercoder** [comment]
@daltonmenezes I still can't get this to work. Any help would be appreciated.

**Comment by daltonmenezes** [comment]
@thesobercoder can you tell me more about the issue? Also, provide me please what terminal you are using and your hyper config file.
